task_1:
	gcc -g  -o task_1 task_1.c
task_2:
	gcc -g  -o task_2 task_2.c
task_3:
	gcc -g -pthread  -o task_3 task_3.c
task_3_2:
	gcc -g -pthread  -o task_3_2 task_3_2.c
task_4:
	gcc -g -pthread  -o task_4 task_4.c