task1: task1.c
	gcc -o task1 task1.c
task2: generic_list.c
	gcc -o task2 generic_list.c
task3: task3.c
	gcc -o task3 task3.c
generic_print:
	gcc -ffast-math -o generic_print generic_print.c
task4: printer.c
	gcc -o task4 printer.c